spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        # show-sql: true
        # format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: "/h2-console"
logging:
  level:
    org:
      hibernate:
        SQL: debug